apiVersion: v1
kind: Pod
metadata:
  name: test-s3
  labels:
    name: test-s3
  annotations:
    iam.amazonaws.com/role: <role-name to assume>
spec:
  containers:
  - image: fstab/aws-cli
    command: ["/bin/bash"]
    args: ["-c", "sleep infinity"]
    name: test-s3